In [1]:
from __future__ import absolute_import, division, print_function, unicode_literals

import pathlib

import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns

try:
  # %tensorflow_version only exists in Colab.
  %tensorflow_version 2.x
except Exception:
  pass

import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers, regularizers

from tensorflow.keras.callbacks import Callback,ModelCheckpoint
from tensorflow.keras.models import Sequential,load_model
from tensorflow.keras.layers import Dense, Dropout
import tensorflow.keras.backend as K


print(pd.__version__)
print(sns.__version__)
print(tf.__version__)
print(keras.__version__)

1.0.0
0.9.0
2.2.0
2.3.0-tf


In [5]:
inputs = tf.random.normal([32, 10, 8])
print(inputs.numpy())

[[[-1.0600638  -0.16822724 -1.507255   ...  0.43750775  1.4840465
   -0.6743138 ]
  [-1.6348277  -0.5173422  -1.8091534  ... -1.388965    1.2588481
    1.1514562 ]
  [-1.078391    0.27874056  0.15022181 ...  1.4065189  -0.5036542
    1.2278649 ]
  ...
  [ 1.5974007  -1.4063836  -1.6469176  ...  0.51098955 -0.56412774
    1.345428  ]
  [ 0.8698043  -0.65996295 -1.179277   ...  0.00968692 -0.7762754
   -0.03370098]
  [-0.09108624  0.05024238 -1.6220081  ... -0.57507575  0.30197287
    0.8176584 ]]

 [[-0.46904737 -0.50117695 -1.0995421  ...  1.0162301   0.8814047
   -1.5405904 ]
  [-0.52100295  0.46770176  1.6746763  ...  1.9019417   0.5850009
    0.4088884 ]
  [-0.06719758 -0.29649338  0.31786388 ... -0.57927674 -0.90539026
    1.0033305 ]
  ...
  [ 0.01508873  0.60324633  0.19885719 ...  1.2118018  -0.52511156
    0.761824  ]
  [-0.02991802 -2.0560346   0.5466562  ...  0.32188582  0.8602329
   -0.1440748 ]
  [-0.1510332  -0.6884254  -1.30492    ... -0.1919744   1.0952272
   -1.5411901 

In [4]:
lstm = tf.keras.layers.LSTM(4)
output = lstm(inputs)
print(output.shape)
print(output.numpy())

(32, 4)
[[ 0.5230584   0.15491666  0.13910806  0.22165377]
 [-0.04467476  0.24415289  0.01469359  0.1419121 ]
 [-0.00612703  0.10981689  0.01437455  0.28335267]
 [ 0.17146856 -0.369679   -0.0529438   0.04614811]
 [ 0.07691537  0.18144488  0.10577153  0.14062272]
 [ 0.24185085 -0.21436964 -0.33810407 -0.05860731]
 [-0.1993589   0.13857354 -0.16854109  0.01141975]
 [-0.11454089 -0.03962806  0.09935914  0.05089455]
 [ 0.15313926 -0.06199316 -0.1044227  -0.34774768]
 [-0.10474315  0.18939328  0.20506081 -0.0343512 ]
 [ 0.09503347  0.45588216  0.09566833  0.35580742]
 [-0.27144462  0.09002487  0.3455428  -0.35640672]
 [-0.06827295 -0.08575293  0.2025684  -0.17051773]
 [-0.19787724  0.38505548  0.1769282   0.19667478]
 [ 0.13620977  0.24369697  0.028774    0.14053452]
 [-0.05885264  0.01872095  0.39609993 -0.12700392]
 [-0.14613482  0.54452765  0.2812765   0.17155445]
 [ 0.36752978 -0.0022365   0.13052161 -0.10766179]
 [-0.2057029   0.07734524  0.07112369 -0.16884889]
 [-0.01057447 -0.277064

In [6]:
lstm = tf.keras.layers.LSTM(4, return_sequences=True, return_state=True)
whole_seq_output, final_memory_state, final_carry_state = lstm(inputs)

print(whole_seq_output.shape)
print(final_memory_state.shape)
print(final_carry_state.shape)


(32, 10, 4)
(32, 4)
(32, 4)
