In [1]:
""" Cholesky decomposition with NumPy """
import numpy as np

A = np.array([[10., -1., 2., 0.],
              [-1., 11., -1., 3.],
              [2., -1., 10., -1.],
              [0.0, 3., -1., 8.]])
B = np.array([6., 25., -11., 15.])

L = np.linalg.cholesky(A)

print(L)

print(np.dot(L, L.T.conj()))  # A=L.L*


y = np.linalg.solve(L, B)  # L.L*.x=B. When L*.x=y, then L.y=B.
print(y)

x = np.linalg.solve(L.T.conj(), y)  # x=L*'.y
print(x)

print(np.mat(A) * np.mat(x).T)  # B=Ax

[[ 3.16227766  0.          0.          0.        ]
 [-0.31622777  3.3015148   0.          0.        ]
 [ 0.63245553 -0.24231301  3.08889696  0.        ]
 [ 0.          0.9086738  -0.25245792  2.6665665 ]]
[[10. -1.  2.  0.]
 [-1. 11. -1.  3.]
 [ 2. -1. 10. -1.]
 [ 0.  3. -1.  8.]]
[ 1.8973666   7.75401642 -3.34135488  2.6665665 ]
[ 1.  2. -1.  1.]
[[  6.]
 [ 25.]
 [-11.]
 [ 15.]]
